swagger: "2.0"
info:
  title: "FastAPI"
  version: "0.0.1"
paths:
  /service/info:
    get:
      summary: Root
      operationId: root_service_info_get
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema: {}
