swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /v1/mesher/health:
    get:
      operationId: Health
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /v1/mesher/metrics:
    get:
      operationId: GetMetrics
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /v1/mesher/routeRule/{serviceName}:
    get:
      operationId: RouteRuleByService
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /v1/mesher/version:
    get:
      operationId: GetVersion
      consumes:
      - '*/*'
      produces:
      - '*/*'
